# Generated by Django 5.1.2 on 2024-11-04 20:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='教練id', primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(help_text='教練姓名', max_length=10)),
                ('school', models.CharField(help_text='所屬學校', max_length=30)),
                ('phone', models.CharField(help_text='聯絡電話', max_length=10)),
                ('mail', models.EmailField(help_text='電子郵件', max_length=50)),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='運動員id', primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(help_text='運動員姓名', max_length=10)),
                ('school', models.CharField(help_text='所屬學校', max_length=30)),
                ('phone', models.CharField(help_text='聯絡電話', max_length=10)),
                ('mail', models.EmailField(help_text='電子郵件', max_length=50)),
                ('guardian', models.CharField(help_text='監護人 (姓名/稱謂)', max_length=10)),
                ('emr_phone', models.CharField(help_text='緊急聯絡電話', max_length=10)),
                ('address', models.CharField(help_text='地址', max_length=50)),
                ('birth', models.DateField(help_text='生日')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.coach')),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='DailyTrainRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='訓練日期')),
                ('distance', models.FloatField(help_text='跑步距離 (公里)')),
                ('time', models.TimeField(help_text='跑步時間')),
                ('description', models.CharField(help_text='訓練描述', max_length=50)),
                ('athlete_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.athlete')),
            ],
            options={
                'ordering': ['-athlete_id', 'date'],
            },
        ),
        migrations.CreateModel(
            name='HurtRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='受傷日期')),
                ('type', models.CharField(help_text='受傷部位', max_length=10)),
                ('description', models.CharField(help_text='受傷描述', max_length=50)),
                ('athlete_id', models.ForeignKey(help_text='運動員id', on_delete=django.db.models.deletion.CASCADE, to='backend.athlete')),
            ],
            options={
                'ordering': ['-athlete_id', 'date'],
            },
        ),
        migrations.CreateModel(
            name='RaceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='比賽日期')),
                ('race_name', models.CharField(help_text='比賽名稱', max_length=10)),
                ('description', models.CharField(help_text='比賽描述', max_length=50)),
                ('athlete_id', models.ForeignKey(help_text='運動員id', on_delete=django.db.models.deletion.CASCADE, to='backend.athlete')),
            ],
            options={
                'ordering': ['-athlete_id', 'date'],
            },
        ),
    ]
