# Generated by Django 5.1.2 on 2024-11-17 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='教練姓名', max_length=10)),
                ('school', models.CharField(help_text='所屬學校', max_length=30)),
                ('phone', models.CharField(help_text='聯絡電話', max_length=10)),
                ('mail', models.EmailField(help_text='電子郵件', max_length=254)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/coach/')),
                ('user', models.ForeignKey(help_text='使用者', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='運動員姓名', max_length=10)),
                ('school', models.CharField(help_text='所屬學校', max_length=30)),
                ('phone', models.CharField(help_text='聯絡電話', max_length=10)),
                ('mail', models.EmailField(help_text='電子郵件', max_length=50)),
                ('guardian', models.CharField(help_text='監護人 (姓名/稱謂)', max_length=10)),
                ('emr_phone', models.CharField(help_text='緊急聯絡電話', max_length=10)),
                ('address', models.CharField(help_text='地址', max_length=50)),
                ('birth', models.DateField(help_text='生日')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/athlete/')),
                ('user', models.ForeignKey(help_text='使用者', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_data.coach')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
