# Generated by Django 5.1.2 on 2024-11-18 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', '男'), ('F', '女'), ('O', '其他')], db_column='性別', default='M', max_length=2)),
                ('name', models.CharField(help_text='運動員姓名', max_length=10)),
                ('school', models.CharField(help_text='所屬學校', max_length=30)),
                ('phone', models.CharField(help_text='聯絡電話', max_length=10)),
                ('mail', models.EmailField(help_text='電子郵件', max_length=50)),
                ('guardian', models.CharField(help_text='監護人 (姓名/稱謂)', max_length=10)),
                ('emr_phone', models.CharField(help_text='緊急聯絡電話', max_length=10)),
                ('address', models.CharField(help_text='地址', max_length=50)),
                ('birth', models.DateField(help_text='生日')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='uploads/athlete/')),
                ('user', models.OneToOneField(help_text='使用者', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tb_athlete',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='教練姓名', max_length=10)),
                ('gender', models.CharField(choices=[('M', '男'), ('F', '女'), ('O', '其他')], db_column='性別', default='M', max_length=2)),
                ('school', models.CharField(help_text='所屬學校', max_length=30)),
                ('phone', models.CharField(help_text='聯絡電話', max_length=10)),
                ('mail', models.EmailField(help_text='電子郵件', max_length=254)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='uploads/coach/')),
                ('user', models.ForeignKey(help_text='使用者', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tb_coach',
                'ordering': ['name'],
                'unique_together': {('name', 'gender', 'phone')},
            },
        ),
        migrations.CreateModel(
            name='Coach_Athlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_athlete_relationships', to='user_data.athlete')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='athlete_coach_relationships', to='user_data.coach')),
            ],
            options={
                'db_table': 'tb_coach_athlete',
                'unique_together': {('athlete', 'coach')},
            },
        ),
        migrations.AddField(
            model_name='athlete',
            name='coach',
            field=models.ManyToManyField(help_text='教練', related_name='athletes', through='user_data.Coach_Athlete', to='user_data.coach'),
        ),
        migrations.AlterUniqueTogether(
            name='athlete',
            unique_together={('name', 'gender', 'phone')},
        ),
    ]
