# Generated by Django 5.1.2 on 2024-11-23 02:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
            ],
            options={
                'db_table': 'tb_link_information',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(help_text='使用者', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('gender', models.CharField(choices=[('M', '男'), ('F', '女'), ('O', '其他')], default='M', max_length=1)),
                ('name', models.CharField(help_text='姓名', max_length=10, null=True)),
                ('school', models.CharField(help_text='所屬學校', max_length=30, null=True)),
                ('phone', models.CharField(help_text='聯絡電話', max_length=10, null=True)),
                ('guardian', models.CharField(help_text='監護人 (姓名/稱謂)', max_length=10, null=True)),
                ('emr_phone', models.CharField(help_text='緊急聯絡電話', max_length=10, null=True)),
                ('address', models.CharField(help_text='地址', max_length=50, null=True)),
                ('birth', models.DateField(help_text='生日', null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='uploads/profilePic/')),
                ('linking', models.ManyToManyField(through='user_data.LinkInformation', to='user_data.userprofile')),
            ],
            options={
                'db_table': 'tb_user_profile',
                'ordering': ['name'],
                'unique_together': {('name', 'gender', 'birth', 'school')},
            },
        ),
        migrations.AddField(
            model_name='linkinformation',
            name='link_A',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_A', to='user_data.userprofile'),
        ),
        migrations.AddField(
            model_name='linkinformation',
            name='link_B',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_B', to='user_data.userprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='linkinformation',
            unique_together={('link_A', 'link_B')},
        ),
    ]
