# Generated by Django 5.1.2 on 2024-11-17 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='athlete',
            old_name='image',
            new_name='avatar',
        ),
        migrations.RenameField(
            model_name='coach',
            old_name='image',
            new_name='avatar',
        ),
    ]
