# Generated by Django 5.1.2 on 2024-11-21 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userprofile',
            table='tb_user_profile',
        ),
    ]
