# Generated by Django 5.1.2 on 2024-11-21 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0002_alter_userprofile_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='isAthlete',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='identity',
            field=models.CharField(choices=[('Ath', '運動員'), ('Coach', '教練')], default='Ath', max_length=5),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('M', '男'), ('F', '女'), ('O', '其他')], default='M', max_length=1),
        ),
    ]
