# Generated by Django 5.1.2 on 2024-11-21 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0003_remove_userprofile_isathlete_userprofile_identity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='mail',
        ),
    ]
