# Generated by Django 5.1.2 on 2024-11-25 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0005_alter_userprofile_emr_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, help_text='電子郵件', max_length=254, null=True),
        ),
    ]
