# Generated by Django 5.1.2 on 2024-11-21 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0005_remove_userprofile_identity'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('link_A', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_A', to='user_data.userprofile')),
                ('link_B', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_B', to='user_data.userprofile')),
            ],
            options={
                'db_table': 'tb_link_information',
                'unique_together': {('link_A', 'link_B')},
            },
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='linking',
            field=models.ManyToManyField(through='user_data.LinkInformation', to='user_data.userprofile'),
        ),
        migrations.DeleteModel(
            name='Coach_Athlete',
        ),
    ]
