# Generated by Django 5.1.2 on 2024-11-25 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0006_userprofile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkinformation',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
