# Generated by Django 5.1.2 on 2024-11-17 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTrainRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='訓練日期')),
                ('distance', models.FloatField(help_text='跑步距離 (公里)')),
                ('time', models.TimeField(help_text='跑步時間')),
                ('description', models.TextField(help_text='訓練描述', max_length=255)),
                ('athlete', models.ForeignKey(help_text='運動員', on_delete=django.db.models.deletion.CASCADE, related_name='daily_train_record', to='user_data.athlete')),
            ],
            options={
                'ordering': ['-athlete', '-date'],
            },
        ),
        migrations.CreateModel(
            name='HurtRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='受傷日期')),
                ('type', models.CharField(help_text='受傷部位', max_length=10)),
                ('description', models.TextField(help_text='受傷描述', max_length=255)),
                ('athlete', models.ForeignKey(help_text='運動員', on_delete=django.db.models.deletion.CASCADE, related_name='hurt_records', to='user_data.athlete')),
            ],
            options={
                'ordering': ['-athlete', 'date'],
            },
        ),
        migrations.CreateModel(
            name='RaceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='比賽日期')),
                ('race_name', models.CharField(help_text='比賽名稱', max_length=10)),
                ('description', models.TextField(help_text='比賽描述', max_length=255)),
                ('athlete', models.ForeignKey(help_text='運動員', on_delete=django.db.models.deletion.CASCADE, related_name='race_record', to='user_data.athlete')),
            ],
            options={
                'ordering': ['-athlete', '-date'],
            },
        ),
    ]
