# Generated by Django 5.1.2 on 2024-11-23 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('record', '0001_initial'),
        ('user_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytrainrecord',
            name='athlete',
            field=models.ForeignKey(help_text='運動員', on_delete=django.db.models.deletion.CASCADE, related_name='daily_train_record', to='user_data.userprofile'),
        ),
        migrations.AddField(
            model_name='hurtrecord',
            name='athlete',
            field=models.ForeignKey(help_text='運動員', on_delete=django.db.models.deletion.CASCADE, related_name='hurt_records', to='user_data.userprofile'),
        ),
        migrations.AddField(
            model_name='racerecord',
            name='athlete',
            field=models.ForeignKey(help_text='運動員', on_delete=django.db.models.deletion.CASCADE, related_name='race_record', to='user_data.userprofile'),
        ),
    ]
