# Generated by Django 5.1.2 on 2024-11-23 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0004_racerecord_proof'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyTrainRecord',
        ),
    ]
