# Generated by Django 5.1.2 on 2024-11-23 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0005_delete_dailytrainrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racerecord',
            name='description',
            field=models.TextField(help_text='比賽描述 (300字以內)', max_length=300),
        ),
        migrations.AlterField(
            model_name='racerecord',
            name='race_name',
            field=models.CharField(help_text='比賽名稱 (30字以內)', max_length=30),
        ),
    ]
