# Generated by Django 5.1.2 on 2024-11-24 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0006_alter_racerecord_description_and_more'),
        ('user_data', '0004_alter_userprofile_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hurtrecord',
            options={'ordering': ['-athlete', 'injure_date']},
        ),
        migrations.AlterUniqueTogether(
            name='hurtrecord',
            unique_together={('athlete', 'injury_type', 'injure_date')},
        ),
        migrations.AlterUniqueTogether(
            name='basicinfo',
            unique_together={('athlete', 'test_date')},
        ),
        migrations.AlterUniqueTogether(
            name='physicaltest',
            unique_together={('athlete', 'test_date')},
        ),
        migrations.AlterUniqueTogether(
            name='racerecord',
            unique_together={('athlete', 'date', 'race_name')},
        ),
        migrations.RemoveField(
            model_name='hurtrecord',
            name='date',
        ),
    ]
