# Generated by Django 5.1.2 on 2024-11-27 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0007_alter_hurtrecord_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='racerecord',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/proof/thumbnail'),
        ),
    ]
