# Generated by Django 5.1.2 on 2024-11-28 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0008_racerecord_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racerecord',
            name='proof',
            field=models.ImageField(blank=True, null=True, upload_to='assets/proof/'),
        ),
        migrations.AlterField(
            model_name='racerecord',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='assets/proof/thumbnail'),
        ),
    ]
